### PR TITLE
treewide: allow dependency selection in a cover letter

### PR DESCRIPTION
**Pull request by ConchuOD**
A lot of series depend on other bits that are in motion, so provide a way for such dependencies to be specificity in a cover letter. The expected format is a line containing "depends on:" followed by lore links to the dependencies. Eg:
depends on:

The regex "(?:depends on|depend(?:a|e)ncies):\n(?:\S+@\S+\n)*" is used to match the line and subsequent links.
Any such matching is best-effort only, and really patchsets should be based on the fixes, master or for-next branches of the riscv tree.

This was suggested by @jones-drew & I finally got around to giving it a proper go. I've tested this on my internal patchwork instance & it looks good...

### CODE REVIEW

**Comment by jones-drew** [comment]
Can you extend the regular expression to also support

Based-on: <message-id>

That would provide compatibility with patchew.

Thanks,
drew

**Comment by jones-drew** [comment]
> Can you extend the regular expression to also support
> 
> Based-on:
> 

Err, that should say

`Based-on: <message-id>`

**Comment by ConchuOD** [comment]
> > Can you extend the regular expression to also support
> > Based-on:
> 
> Err, that should say
> 
> `Based-on: <message-id>`

So all on one line, and always a "Based-on:" prefix, a la git trailer formatting?
If I'm doing that, I should also add "Depends-on:" variant.
The annoying part to test is adding the infra to the poller itself, testing the regex -> pre-reqs applied isn't too hard, so I should be able to extend it like that without too much trouble. Touch wood.

**Comment by jones-drew** [comment]
> > Err, that should say
> > `Based-on: <message-id>`
> 
> So all on one line, and always a "Based-on:" prefix, a la git trailer formatting?

I wasn't sure how to answer this question, since I just pulled that syntax out of an email from someone instructing someone else how to use it. Searching for the answer, I found this thread, which is old, but may help clarify what patchew [probably] handles

https://lists.gnu.org/archive/html/qemu-devel/2017-08/msg01288.html

Without looking closely at the patchew code I can only say that the prefix must be "Based-on:", but it's matched case insensitive.

**Comment by ConchuOD** [comment]
> > > Err, that should say
> > > `Based-on: <message-id>`
> > 
> > 
> > So all on one line, and always a "Based-on:" prefix, a la git trailer formatting?
> 
> I wasn't sure how to answer this question, since I just pulled that syntax out of an email from someone instructing someone else how to use it. Searching for the answer, I found this thread, which is old, but may help clarify what patchew [probably] handles
> 
> https://lists.gnu.org/archive/html/qemu-devel/2017-08/msg01288.html
> 
> Without looking closely at the patchew code I can only say that the prefix must be "Based-on:", but it's matched case insensitive.

Looks like git trailer style, I can add that too I suppose.

**Comment by ConchuOD** [comment]
Been sick for the last week, so finally got around to this. Should be working now for both styles w/ based-on.

**Comment by ConchuOD** [comment]
Given the time delay without a review, I'm just gonna merge this and see what (if anything) breaks.

**Comment by ConchuOD** [comment]
> Given the time delay without a review, I'm just gonna merge this and see what (if anything) breaks.

I did in fact break everything by doing that. Whoops.

**Pull request merged**
